services:
  backend:
    build: ./backend
    env_file: .env
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "5173:80"
